version: '2.1'
networks:
  kafka-net:
    driver: bridge
services:
 zookeeper-1:
   image: confluentinc/cp-zookeeper:latest
   container_name: vuk-zoo-1
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 22181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
   network_mode: host
   extra_hosts:
     - "moby:127.0.0.1"

 zookeeper-2:
   image: confluentinc/cp-zookeeper:latest
   container_name: vuk-zoo-2
   environment:
     ZOOKEEPER_SERVER_ID: 2
     ZOOKEEPER_CLIENT_PORT: 32181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
   network_mode: host
   extra_hosts:
     - "moby:127.0.0.1"

 zookeeper-3:
   image: confluentinc/cp-zookeeper:latest
   container_name: vuk-zoo-3
   environment:
     ZOOKEEPER_SERVER_ID: 3
     ZOOKEEPER_CLIENT_PORT: 42181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
   network_mode: host
   extra_hosts:
     - "moby:127.0.0.1"
 kafka-1:
   image: confluentinc/cp-kafka:latest
   container_name: vuk-kafka-1
   network_mode: host
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.104.66.169:19092
   ports:
     - "19092:19092"
   extra_hosts:
     - "moby:127.0.0.1"

 kafka-2:
   image: confluentinc/cp-kafka:latest
   container_name: vuk-kafka-2
   network_mode: host
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.104.66.169:29092
   ports:
     - "29092:29092"
   extra_hosts:
     - "moby:127.0.0.1"

 kafka-3:
   image: confluentinc/cp-kafka:latest
   container_name: vuk-kafka-3
   network_mode: host
   depends_on:
     - zookeeper-1
     - zookeeper-2
     - zookeeper-3
   environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.104.66.169:39092
   ports:
     - "39092:39092"
   extra_hosts:
     - "moby:127.0.0.1"